cp 01
Holy-Raven/java-filmorate pull request #1
Opened 2023-03-21 18:38 UTC by Holy-Raven

2023-03-22 18:22 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай поправим что отметил и будет зачет:

- текст исключений на англ + Логи на англ


Ниже кину код как еще можно тесты писать, это не призыв, а вариант:
```java
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-03-22 18:22 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<artifactId>simpleclient_servlet_jakarta</artifactId>
Для чего эта зависимость?

2023-03-22 18:22 UTC, krylov-sergey-sergeevich commented on pom.xml
> +	<dependencies>
Версии библиотек можно и рекомендую вынести в проперти

2023-03-22 18:22 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Logger log = LoggerFactory.getLogger(FilmController.class);
лучше аннотацию логгера от ломбока

2023-03-22 18:22 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        filmController = new FilmController();
Не лучший подход, но на пару ближайших домашек его хватит

2023-03-22 18:30 UTC, Holy-Raven commented on pom.xml
> +			<artifactId>simpleclient_servlet_jakarta</artifactId>
без этого аннотации не работали на 11 JDK

2023-03-22 19:01 UTC, Holy-Raven commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        filmController = new FilmController();
Нам пока ничего другого не рассказали, пока оставлю как есть.

2023-03-22 19:03 UTC, Holy-Raven commented
текст логов и исключений перевела. Создание объектов через builder изучу, буду в дальнейшем пользоваться.

2023-03-23 07:39 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет!

2023-03-23 18:50 UTC, merged