Add database
Holy-Raven/java-filmorate pull request #5
Opened 2023-05-03 17:14 UTC by Holy-Raven

2023-05-04 08:20 UTC, krylov-sergey-sergeevich requested changes
Привет, работа неплохая, но давай обсудим и подкорректируем что отмечено.

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    public FilmService(@Qualifier("FilmDbStorage") FilmStorage filmStorage, MpaStorage mpaStorage1, GenreStorage genreStorage, LikeStorage likeStorage) {
Давай вместо конструктора будем аннотацию из ломбока использовать  @requiredargsconstructor

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        log.info("List popular Films");
лог малоинформативный - любой лог должен нести пользу и информацию

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/genre/GenreService.java
> +        log.info("All list GENRE");
Наверно все же Get all list Genre

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/friendship/FriendshipDbStorage.java
> +    private final Logger log = LoggerFactory.getLogger(FilmDbStorage.class);
чем логгер от ломбока не устроил?

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Можно вот так, местами переусложнено как будто:

```
create table if not exists USERS (
    user_id  integer not null primary key auto_increment,
    email    varchar(255) not null,
    login    varchar(255) not null,
    name     varchar(255),
    birthday date,
    deleted  bool default false,
    constraint USER_PK primary key (user_id)
);
```

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
зашивать излишне много логики на уровне бд это не есть хорошо, ибо ей придется думать и делать проверки каждый раз, поэтому можно ставить только реально важные ограничения

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
create unique index if not exists USER_EMAIL_UINDEX on USERS (email);
create unique index if not exists USER_LOGIN_UINDEX on USERS (login);

индексы если еще не учили, то на будущее

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS friendship (
Не до конца понял зачем статус?

```
create table if not exists FRIENDS (
    user_id   int not null references USERS,
    friend_id int not null references USERS,

    PRIMARY KEY (USER_ID,FRIEND_ID)
);
```

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS films (
Тоже показываю как можно, это не значит что надо обязательно менять, просто как пример для наглядности:

```
create table if not exists FILMS (
    film_id     int not null primary key auto_increment,
    name        varchar(255),
    description varchar(200),
    release_date date,
    rate        int,
    duration    int,
    mpa_id      int references MPA(mpa_id),
    deleted     bool default false,
    constraint FILM_PK primary key (film_id)
);
```

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/resources/data.sql
Можно делать вот так:

```
merge into GENRES (genre_id, name)
values (1, 'Комедия'),
       (2, 'Драма'),
       (3, 'Мультфильм'),
       (4, 'Триллер'),
       (5, 'Документальный'),
       (6, 'Боевик');

merge into MPA (mpa_id, name)
values (1, 'G'),
       (2, 'PG'),
       (3, 'PG-13'),
       (4, 'R'),
       (5, 'NC-17');
```

2023-05-04 08:20 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/util/Constant.java
Мапперы это все же не константы, я бы их отдельно держал бы

2023-05-04 15:06 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @Autowired
исправила. но мне на самом деле нагляднее с конструктором, думаю дело привычки.

2023-05-04 15:06 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
исправила

2023-05-04 15:07 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
тут просто казалось что можно сделать исключение, в смысле что другие поля это как строки в таблице, а эти две коллекции как бы не такие,

2023-05-04 15:30 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        log.info("List popular Films");
принято, исправила.

2023-05-04 15:36 UTC, Holy-Raven commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
да, как будем проходить вспомню - подсмотрю.

2023-05-04 15:40 UTC, Holy-Raven commented on src/main/resources/schema.sql
Я спрашивала об этом на вэбинаре, зачем это делать? Если мы вносим туда данные уже проверенные. Но сказали лучше сделать чем нет, как еще один уровень защиты. Я как поняла, это на случай если с нашей БД будет работать не только мое приложение, и какое то еще где хороших проверок может не быть (ну это как я поняла) В общем добавила по максимум, вот только проверка емайла LIKE %@%, у меня что-то не работала, пришлось без нее.

2023-05-04 16:27 UTC, Holy-Raven commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +            filmStorage.delGenresListFromFilm(film.getId());
Должно да (проверила - работает и без нее), но идея была такая, что у меня все настройки в БД скорее как дополнение к логике, на случай если основная бизнес логика даст сбой, потому и это тут оставила.

2023-05-05 06:37 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет ! =)

2023-05-18 08:20 UTC, merged